### ISSUE TITLE
拿不到驗證碼圖片

### ISSUE THREAD

**Issue by HSUTINGHSUAN1994** [BreezeWhite/THSR-Ticket#1]
卡在拿驗證碼圖片那個步驟沒辦法使用

**Comment by BreezeWhite** [comment]
修好了，可以pull master再試一次看看
感謝你的提醒~

**Comment by 108360232Zijie** [comment]
我也有遇到同樣的問題
等待驗證碼...
Traceback (most recent call last):
  File "/content/THSR-Ticket/thsr_ticket/main.py", line 19, in <module>
    main()
  File "/content/THSR-Ticket/thsr_ticket/main.py", line 11, in main
    flow.run()
  File "/usr/local/lib/python3.7/dist-packages/thsr_ticket/controller/booking_flow.py", line 55, in run
    self.book_form.seat_prefer = parse_seat_prefer_value(book_page)
  File "/usr/local/lib/python3.7/dist-packages/thsr_ticket/controller/booking_flow.py", line 155, in parse_seat_prefer_value
    return page.find(**BOOKING_PAGE["seat_prefer_radio"]).attrs['value']
AttributeError: 'NoneType' object has no attribute 'attrs'
