### ISSUE TITLE
Crash while No available train(s)

### ISSUE THREAD

**Issue by smailzhu** [BreezeWhite/THSR-Ticket#6]
```
No available train!
Traceback (most recent call last):
  File "thsr_ticket/main.py", line 15, in <module>
    result = flow.run()
  File "./thsr_ticket/controller/booking_flow.py", line 62, in run
    value = avail_trains[sel-1].form_value  # Selection from UI count from 1
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
```

Check the length of available trains list before continue?

https://github.com/BreezeWhite/THSR-Ticket/blob/499359f24f02daa69acbe72d8e7396221c868899/thsr_ticket/controller/booking_flow.py#L62

**Comment by BreezeWhite** [comment]
Fixed
